################################################################################
# Automatically-generated file. Do not edit!
################################################################################

INO_SRCS := 
ASM_SRCS := 
O_UPPER_SRCS := 
CPP_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
PDE_SRCS := 
CC_SRCS := 
AR_SRCS := 
C_SRCS := 
C_UPPER_DEPS := 
PDE_DEPS := 
C_DEPS := 
AR := 
CC_DEPS := 
AR_OBJ := 
C++_DEPS := 
LINK_OBJ := 
CXX_DEPS := 
ASM_DEPS := 
HEX := 
INO_DEPS := 
SIZEDUMMY := 
S_UPPER_DEPS := 
ELF := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
core/core \
core/core/libb64 \
core/core/spiffs \
core/core/umm_malloc \
libraries/ArduinoOTA \
libraries/ArduinoOTA/examples/BasicOTA \
libraries/ArduinoOTA/examples/OTALeds \
libraries/DallasTemperature \
libraries/DallasTemperature/examples/Alarm \
libraries/DallasTemperature/examples/AlarmHandler \
libraries/DallasTemperature/examples/Multibus_simple \
libraries/DallasTemperature/examples/Multiple \
libraries/DallasTemperature/examples/Simple \
libraries/DallasTemperature/examples/Single \
libraries/DallasTemperature/examples/Tester \
libraries/DallasTemperature/examples/TwoPin_DS18B20 \
libraries/DallasTemperature/examples/WaitForConversion \
libraries/DallasTemperature/examples/WaitForConversion2 \
libraries/DallasTemperature/examples/oneWireSearch \
libraries/DallasTemperature/examples/setUserData \
libraries/EEPROM \
libraries/EEPROM/examples/eeprom_clear \
libraries/EEPROM/examples/eeprom_read \
libraries/EEPROM/examples/eeprom_write \
libraries/ESP8266HTTPClient/examples/Authorization \
libraries/ESP8266HTTPClient/examples/BasicHttpClient \
libraries/ESP8266HTTPClient/examples/ReuseConnection \
libraries/ESP8266HTTPClient/examples/StreamHttpClient \
libraries/ESP8266HTTPClient/src \
libraries/ESP8266WebServer/examples/AdvancedWebServer \
libraries/ESP8266WebServer/examples/FSBrowser \
libraries/ESP8266WebServer/examples/HelloServer \
libraries/ESP8266WebServer/examples/HttpBasicAuth \
libraries/ESP8266WebServer/examples/SDWebServer \
libraries/ESP8266WebServer/examples/SimpleAuthentification \
libraries/ESP8266WebServer/examples/WebUpdate \
libraries/ESP8266WebServer/src \
libraries/ESP8266WiFi/examples/HTTPSRequest \
libraries/ESP8266WiFi/examples/NTPClient \
libraries/ESP8266WiFi/examples/WiFiAccessPoint \
libraries/ESP8266WiFi/examples/WiFiClient \
libraries/ESP8266WiFi/examples/WiFiClientBasic \
libraries/ESP8266WiFi/examples/WiFiClientEvents \
libraries/ESP8266WiFi/examples/WiFiMulti \
libraries/ESP8266WiFi/examples/WiFiScan \
libraries/ESP8266WiFi/examples/WiFiTelnetToSerial \
libraries/ESP8266WiFi/examples/WiFiWebServer \
libraries/ESP8266WiFi/src \
libraries/ESP8266httpUpdate/examples/httpUpdate \
libraries/ESP8266httpUpdate/examples/httpUpdateSPIFFS \
libraries/ESP8266httpUpdate/src \
libraries/ESP8266mDNS \
libraries/ESP8266mDNS/examples/OTA-mDNS-SPIFFS \
libraries/ESP8266mDNS/examples/mDNS-SD_Extended \
libraries/ESP8266mDNS/examples/mDNS_Web_Server \
libraries/OneWire \
libraries/OneWire/examples/DS18x20_Temperature \
libraries/OneWire/examples/DS2408_Switch \
libraries/OneWire/examples/DS250x_PROM \
libraries/SD/examples/CardInfo \
libraries/SD/examples/Datalogger \
libraries/SD/examples/DumpFile \
libraries/SD/examples/Files \
libraries/SD/examples/ReadWrite \
libraries/SD/examples/listfiles \
libraries/SD/src \
libraries/SD/src/utility \
libraries/SPI \
libraries/Ticker \
libraries/Ticker/examples/TickerBasic \
libraries/Ticker/examples/TickerParameter \

